# roles/dotfiles/tasks/main.yml
# タスク定義
- block:
  - name: create git clone dir
    command:
      # mkdir -p で存在しない時だけディレクトリを作成する
      cmd: mkdir -p {{ directory.clone_path }}
  - name: git clone dotfiles
    ansible.builtin.git:
      repo: git@github.com:watame/dotfiles.git
      dest: "{{ directory.clone_path }}"
  - name: copy dotfiles to homedir
    command:
      cmd: cp -r {{ directory.clone_path }}/{{ item }} {{ directory.dest_path }}
    # roles/dotfiles/tasks/main.yml 内の dotfiles を読み込む
    with_items: "{{ dotfiles }}"
  - name: remove git clone dir
    command:
      cmd: rm -rf {{ directory.clone_path }}

  # CLIのコマンドだけインストールしたいときもあると思うのでTagを追加する
  # https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_tags.html
  tags:
    - dotfiles
