# roles/dotfiles/tasks/main.yml
# タスク定義
- block:
  - name: git colone dotfiles
  - name: copy dotfiles to homedir

  # CLIのコマンドだけインストールしたいときもあると思うのでTagを追加する
  # https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_tags.html
  tags:
    - dotfiles
