# roles/preference/tasks/main.yml
# タスク定義
- block:
  - name: apply mac preference
    command:
      cmd: "{{ item.command }}"
    # roles/preference/tasks/main.yml 内の commands を読み込む
    with_items: "{{ commands }}"

  # CLIのコマンドだけインストールしたいときもあると思うのでTagを追加する
  # https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_tags.html
  tags:
    - preference
