# roles/homebrew/tasks/main.yml
# タスク定義
- block:
  - name: homebrew update/upgrade
    homebrew:
      update_homebrew: true
      upgrade_all: yes

  - name: homebrew tap
    homebrew_tap:
      name: "{{ item }}"
      state: present
    # roles/homebrew/tasks/main.yml 内の taps を読み込む
    with_items: "{{ taps }}"

  - name: homebrew install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    # roles/homebrew/tasks/main.yml 内の packages を読み込む
    with_items: "{{ packages }}"

  # CLIのコマンドだけインストールしたいときもあると思うのでTagを追加する
  # https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_tags.html
  tags:
    - homebrew
