# roles/initialize_shell/tasks/main.yml
# タスク定義
- block:
  - name: install oh my zsh
    # shellを起動したいため、shellモジュールを用いて実施
    # https://kakts-tec.hatenablog.com/entry/2017/04/24/004904
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  # CLIのコマンドだけインストールしたいときもあると思うのでTagを追加する
  # https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_tags.html
  tags:
    - initialize_shell
