# roles/homebrew_cask/tasks/main.yml
# タスク定義
- block:
  - name: homebrew cask install
    environment:
      HOMEBREW_CASK_OPTS: --appdir=/Applications
    homebrew_cask:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    # roles/homebrew_cask/tasks/main.yml 内の packages を読み込む
    with_items: "{{ packages }}"

  # CLIのコマンドだけインストールしたいときもあると思うのでTagを追加する
  # https://docs.ansible.com/ansible/2.9_ja/user_guide/playbooks_tags.html
  tags:
    - homebrew_cask
